#!/usr/bin/env bash
# this script Install and configure HAproxy on lb-01 server

# install haproxy
sudo apt update
sudo apt install haproxy

# Configure haproxy
balancer='defaults
	mode http
	timeout client 10s
	timeout connect 5s
	timeout server 10s 
	timeout http-request 10s

frontend myfrontend
	bind *:80
	default_backend servers

backend webservers
	balance roundrobin
	server 483739-web-01 52.91.133.80:80 check
	server 483739-web-02 54.90.38.203:80 check
'

# add to config
echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Restart haproxy
sudo service haproxy restart
