#!/usr/bin/env bash
# this script Install and configure HAproxy on lb-01 server

# Configure haproxy
balancer='defaults
	mode http
	timeout client 10s
	timeout connect 5s
	timeout server 10s 
	timeout http-request 10s

frontend myfrontend
	bind *:80
	default_backend webservers

backend webservers
	balance roundrobin
	server 483739-web-01 52.91.133.80:80 check
	server 483739-web-02 54.90.38.203:80 check


# Update packages
sudo apt-get -y update
sudo apt-get -y upgrade

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy

# add to config
sudo echo "$balancer" >> /etc/haproxy/haproxy.cfg

# Restart haproxy
sudo systemctl enable haproxy
sudo systemctl restart haproxy
